[env]
_.path = ["node_modules/.bin"]

[tasks]
dev = "pnpm -r dev"
test = "pnpm -r test"
lint = "pnpm -r lint"
clean = ["pnpm -r clean"]
fmt = "biome check --fix --unsafe ."

[tasks.build]
run = ["tsc --build", "pnpm -r build"]
depends_post = ["fmt"]

[tasks.release]
run = "changeset publish"
depends = ["build"]

[tasks.example]
run = "pnpm --filter ./examples/{{arg(name=\"example\")}} run dev"

[tools]
pnpm = "9.15.1"
